### ISSUE TITLE
Shouldn't state.arcs return a *new* iterator?

### ISSUE THREAD

**Issue by lebigot** [vchahun/pyfst#11]
Currently, the arcs of a state, `state.arcs`, return an iterator, but not a new one. As a consequence, different pieces of code might interfere if they do not take the precaution of resetting the iterator each time. For instance, getting the arcs of a linear chain must currently be done with

```
arcs = (next(iter(state.arcs)) for state in shortest_path)
```

where `iter()` reinitializes the iterator `state.arcs`. Wouldn't it be more natural to have `state.arc` return a new iterator each time?

**Comment by vchahun** [comment]
I am not sure to understand this. It looks to me like state.arcs is actually a new iterator:

``` python
    property arcs:
        """state.arcs: all the arcs starting from this state"""
        def __get__(self):
            return iter(self)
```

Do you have an example of something that does not work without calling iter()?
