### ISSUE TITLE
pip install pyfst does not work on Mavericks

### ISSUE THREAD

**Issue by estherklabbers** [vchahun/pyfst#15]
When I tried to install a clean install of pyfst on my new 2013 Haswell Macbook Pro that came with Mavericks it would not install because it could not find tr1/unordered_map.

Looking at some similar problems I downloaded pyfst.0.2.3.tar gz and added the option '-stdlib=libstdc++' to setup.py, then ran python setup.py install. That seemed to work. But now when I open python (installed via Homebrew) I get the following error:

> > > import fst
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/site-packages/fst/**init**.py", line 1, in <module>
> > >     from fst._fst import EPSILON, EPSILON_ID, SymbolTable,\
> > > ImportError: dlopen(/usr/local/lib/python2.7/site-packages/fst/_fst.so, 2): Symbol not found: __ZNSiD0Ev
> > >   Referenced from: /usr/local/lib/libfst.1.dylib
> > >   Expected in: flat namespace
> > >  in /usr/local/lib/libfst.1.dylib

**Comment by vchahun** [comment]
Try to run:

```
otool -L /usr/local/lib/python2.7/site-packages/fst/_fst.so
```

to see what library is missing

**Comment by estherklabbers** [comment]
I have openfst installed through Macports. They upgraded the version recently to work with Mavericks. _fst.so is located in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fst

when I run otool -L /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fst/_fst.so I get:

_fst.so:
    /usr/local/lib/libfst.1.dylib (compatibility version 2.0.0, current version 2.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

At this time when I try to run pip install pyfst I get a different error. And when I run python setup.py install in pyfst-0.2.3 it seems to work but when I open python and say import fat it wants to load libfst from the /usr/local/lib location instead of /opt/local/lib. And if I create a symbolic link in /usr/local/lib to libfst I get the same error as before where it can't find that symbol.

**Comment by vchahun** [comment]
If you have two versions of OpenFst installed, things will get tricky. It seems that you linked against the macports library but when you load the library it finds the library in /usr/local/lib and ignores the macports library.
I highly recommend using only a single version of OpenFst.

**Comment by estherklabbers** [comment]
Thank you for your response. I only have one version of openfst installed, the macports version. But somehow pyfst still wants to find the libfst.1.dylib file in /usr/local/lib. As I said, even with a clean install “pip install pyfst” does not work under Mavericks.

What is the best way to compile it from scratch? Am I doing the right thing by trying to run “python setup.py install”?

Esther

On Nov 25, 2013, at 11:34 AM, Victor Chahuneau <notifications@github.com<mailto:notifications@github.com>> wrote:

If you have two versions of OpenFst installed, things will get tricky. It seems that you linked against the macports library but when you load the library it finds the library in /usr/local/lib and ignores the macports library.
I highly recommend using only a single version of OpenFst.
