### ISSUE TITLE
cannot import fst module

### ISSUE THREAD

**Issue by archibaldhaddock** [vchahun/pyfst#16]
Hello everybody !

I tried to install pyfst this morning...I got the following problem : 
My test script fails at the very first "import" line...

import fst

Traceback (most recent call last):
  File "testfst.py", line 1, in <module>
    import fst
  File "/usr/local/lib/python2.6/dist-packages/fst/**init**.py", line 1, in <module>
    from fst._fst import EPSILON, EPSILON_ID, SymbolTable,\
ImportError: libfst.so.0: cannot open shared object file: No such file or directory

Indeed, there is no libfst.so.0 on my disk....The installation of openfst library has populated /usr/local/lib with : 

-rw-r--r-- 1 root staff 282595604 27 févr. 08:54 libfstscript.a
-rwxr-xr-x 1 root staff   6615292 27 févr. 09:05 libfst.so.1.0.0
lrwxrwxrwx 1 root staff        15 27 févr. 09:05 libfst.so.1 -> libfst.so.1.0.0
lrwxrwxrwx 1 root staff        15 27 févr. 09:05 libfst.so -> libfst.so.1.0.0
-rwxr-xr-x 1 root staff 109946159 27 févr. 09:05 libfstscript.so.1.0.0
lrwxrwxrwx 1 root staff        21 27 févr. 09:05 libfstscript.so.1 -> libfstscript.so.1.0.0
lrwxrwxrwx 1 root staff        21 27 févr. 09:05 libfstscript.so -> libfstscript.so.1.0.0
-rwxr-xr-x 1 root staff       960 27 févr. 09:05 libfstscript.la
-rwxr-xr-x 1 root staff       924 27 févr. 09:05 libfst.la

I tried "pip uninstall pyfst" and then "pip install pyfst" with the same result...

What am I doing wrong ?

**Comment by redpony** [comment]
What OS are you working with?

**Comment by arne-cl** [comment]
I've got almost the same problem. I'm running Linux Mint 16 (64bit) and I installed `pyfst 0.2.3` via pip. This is error I get when I try to import fst:

```
$ ~/repos/decparse/src/decparse $ python2.7 
Python 2.7.6 |Anaconda 1.9.1 (64-bit)| (default, Jan 17 2014, 10:13:17) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fst
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python2.7/site-packages/fst/__init__.py", line 1, in <module>
    from fst._fst import EPSILON, EPSILON_ID, SymbolTable,\
ImportError: libfst.so.1: cannot open shared object file: No such file or directory
>>>
```

`libfst.so.1` is installed, though:

```
$ ~/repos/decparse/src/decparse $ ls -l /usr/local/lib/libfst*
-rwxr-xr-x 1 root root     924 Apr 26 17:11 /usr/local/lib/libfst.la
lrwxrwxrwx 1 root root      15 Apr 26 17:11 /usr/local/lib/libfst.so -> libfst.so.1.0.0
lrwxrwxrwx 1 root root      15 Apr 26 17:11 /usr/local/lib/libfst.so.1 -> libfst.so.1.0.0
-rwxr-xr-x 1 root root 6560289 Apr 26 17:11 /usr/local/lib/libfst.so.1.0.0
```

**Comment by dbonadiman** [comment]
I have actually the same problem on OS X 10.9.3

**Comment by bago89** [comment]
Hi, I solved this problem on ubuntu execute this command in terminal "ldconfig"

**Comment by arne-cl** [comment]
Thanks @bago89, `sudo ldconfig` seemed to do the trick on Linux Mint.
