### ISSUE TITLE
Strange Symbol Table 

### ISSUE THREAD

**Issue by puuzll** [vchahun/pyfst#17]
Hi,I installed pyfst use 'pip install pyfst --user' and my openfst version is 1.3.4
There is strange In this case :

> import fst
> symbolTable = fst.SymbolTable()
> symbolTable[u'<eps>'] = 0
> symbolTable[u'</s>'] = 1
> print [(a,b) for a,b in symbolTable.items()] 

[(u'<eps>', 0), (u'<eps>', 0), (u'</s>', 1)]  ### there are two u'<eps>'??

> symbolTable.write('sym.table')
> symbolTable1 = fst.read_symbols('sym.table')
> print [(a,b) for a,b in symbolTable1.items()]

[(u'</s>', 1), (u'\u03b5', 0), (u'\u03b5', 0)] ### u'<eps>' has been changed to u'\u03b5'??

PS:If I subtitued u'</s>' with u'a' , the output is right.

**Comment by vchahun** [comment]
By default, a symbol table assigns the unicode character ε (u'\u03b5') to 0. In your case, you want to do:

``` python
symbolTable = fst.SymbolTable(epsilon='<eps>')
```
