### ISSUE TITLE
Feature Request: Simpler interface for shortest_path

### ISSUE THREAD

**Issue by dan-blanchard** [vchahun/pyfst#2]
This may be mine own relative ignorance when it comes to OpenFST, but to me it would make things a lot more Pythonic if shortest_path return a list of paths (represented as lists of input/output tuples) instead of returning an FST.

For a project I'm working on I'd like to get the n-best paths through an FSA, and it's not immediately clear to me how I would go about building a list representation of all the paths easily given the current interface.

Any help you could offer would be greatly appreciated.

**Comment by wilkeraziz** [comment]
Hi,

there are many reasons why one would need the FST representation of the n-best list, besides being compact it allows one to rely on FST operations.
If you want to get the list of paths you can do like this:

``` python
nbest = fsa.shortest_path(10) # gets an FSA that encodes 10-best paths
for path in nbest.paths(): # enumerates complete paths in 'nbest'
    print [x.ilabel for x in path] # the path returned is the sequence of arcs along that path
```

this procedure `paths` is not in victor's repo, but you can get it from mine, have a look at line 650: https://github.com/wilkeraziz/pyfst/blob/master/pyfst/fst.pyx

**Comment by dan-blanchard** [comment]
Your `paths` method solves the big problem I was having trying to implement this myself, so thanks so much for that!
