### ISSUE TITLE
cannot install pyfst

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [vchahun/pyfst#31]
Hi

I used pip to install pyfst and encountered by following error:

> Collecting pyfst
  Using cached pyfst-0.2.3.tar.gz
Building wheels for collected packages: pyfst
  Running setup.py bdist_wheel for pyfst ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-N3M71s/pyfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgPRLh4pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/fst
  copying fst/__init__.py -> build/lib.linux-x86_64-2.7/fst
  running build_ext
  building 'fst._fst' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/fst
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c fst/_fst.cpp -o build/temp.linux-x86_64-2.7/fst/_fst.o -O2
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  fst/_fst.cpp:321:30: fatal error: fst/symbol-table.h: No such file or directory
   #include <fst/symbol-table.h>
                                ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  Failed building wheel for pyfst
  Running setup.py clean for pyfst
Failed to build pyfst
Installing collected packages: pyfst
  Running setup.py install for pyfst ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-N3M71s/pyfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XNPHYl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fst
    copying fst/__init__.py -> build/lib.linux-x86_64-2.7/fst
    running build_ext
    building 'fst._fst' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/fst
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c fst/_fst.cpp -o build/temp.linux-x86_64-2.7/fst/_fst.o -O2
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    fst/_fst.cpp:321:30: fatal error: fst/symbol-table.h: No such file or directory
     #include <fst/symbol-table.h>
                                  ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-N3M71s/pyfst/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XNPHYl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-N3M71s/pyfst/

I also get git repository by git clone and still cannot install it from source:

> running install
running build
running build_py
running build_ext
building 'fst._fst' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c fst/_fst.cpp -o build/temp.linux-x86_64-2.7/fst/_fst.o -O2
x86_64-linux-gnu-gcc: error: fst/_fst.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

any help is appreciated...

**Comment by 0xnurl** [comment]
Did you try `export CFLAGS="-std=c++11"`?

**Comment by mohamad-hasan-sohan-ajini** [comment]
Sorry for latency. I test it but there is no change!! Still get the same errors

**Comment by mohamad-hasan-sohan-ajini** [comment]
The problem was solved by updating openFst to 1.3 version
