### ISSUE TITLE
setup.py install fails on Mac OS X

### ISSUE THREAD

**Issue by lebigot** [vchahun/pyfst#5]
python setup.py install fails on Mac OS X (with openfst installed through MacPort's, if this matters):

```
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -O2 -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c fst/_fst.cpp -o build/temp.macosx-10.7-x86_64-2.7/fst/_fst.o -O2
clang: error: no such file or directory: 'fst/_fst.cpp'
clang: error: no input files
```

I does not look like _fst.cpp can be found anywhere on my Mac…

**Comment by vchahun** [comment]
It looks like you are trying to install pyfst directly from the git repository, which does not contain the _fst.cpp file required to compile the python module. This file is [generated automatically](https://github.com/vchahun/pyfst/wiki/Contributing) from the Cython source.
If you just want to install pyfst without making changes, use:

``` bash
pip install pyfst
```

**Comment by lebigot** [comment]
`pip install pyfst` was not working either, which is why I tried to install through git directly.

However, `pip-2.7 install pyfst` now works on my Mac OS X with MacPorts, so I'm happy. Thanks! :)

**Comment by ruohoruotsi** [comment]
@lebigot  which version of openfst are you using?
