### ISSUE TITLE
Code lines are too long

### ISSUE THREAD

**Issue by lebigot** [vchahun/pyfst#9]
You may want to consider limiting the lines in your code to 79 characters, as per PEP 8. This would make the code easier to read (in the numerous editors that are 80 character wide by default).

**Comment by vchahun** [comment]
I will try to stick to this limit as much as possible, but I will not not strictly enforce it as line like these:

``` C++
cdef libfst.{{arc}}RandGenOptions* options = new libfst.{{arc}}RandGenOptions(selector)
```

are hard to break.
